#pragma once

#include "exceptions.hpp"
#include "utils.hpp"

#pragma pack(push)

#include "il2cpp-api-types.h"
#include "il2cpp-class-internals.h"
#include "il2cpp-metadata.h"
#include "il2cpp-object-internals.h"
#include "il2cpp-tabledefs.h"
#include "vm/GlobalMetadataFileInternals.h"

#include <cstddef>
#include <vector>
#include <stdio.h>
#include <stdlib.h>

typedef std::vector<Il2CppAssembly const*> Il2CppAssemblyVector;

#define API_FUNC(rt, name, ...) \
    extern rt (*name) __VA_ARGS__;

// A (once) class which contains all available il2cpp functions
// Created by zoller27osu
namespace i2c::functions {
// These methods autogenerated by Sc2ad:
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(int, init, (const char* domain_name));
    API_FUNC(int, init_utf16, (Il2CppChar const* domain_name));
#else
    API_FUNC(void, init, (const char* domain_name));
    API_FUNC(void, init_utf16, (Il2CppChar const* domain_name));
#endif
    API_FUNC(void, shutdown, ());
    API_FUNC(void, set_config_dir, (char const* config_path));
    API_FUNC(void, set_data_dir, (char const* data_path));
    API_FUNC(void, set_temp_dir, (char const* temp_path));
    API_FUNC(void, set_commandline_arguments, (int argc, char const* const argv[], char const* basedir));
    API_FUNC(void, set_commandline_arguments_utf16, (int argc, Il2CppChar const* const argv[], char const* basedir));
    API_FUNC(void, set_config_utf16, (Il2CppChar const* executablePath));
    API_FUNC(void, set_config, (char const* executablePath));
    API_FUNC(void, set_memory_callbacks, (Il2CppMemoryCallbacks * callbacks));
    API_FUNC(Il2CppImage const*, get_corlib, ());
    API_FUNC(void, add_internal_call, (char const* name, Il2CppMethodPointer method));
    API_FUNC(Il2CppMethodPointer, resolve_icall, (char const* name));
    API_FUNC(void*, alloc, (size_t size));
    API_FUNC(void, free, (void* ptr));
    API_FUNC(Il2CppClass*, array_class_get, (Il2CppClass * element_class, uint32_t rank));
    API_FUNC(uint32_t, array_length, (Il2CppArray * array));
    API_FUNC(uint32_t, array_get_byte_length, (Il2CppArray * array));
    API_FUNC(Il2CppArray*, array_new, (Il2CppClass * elementTypeInfo, il2cpp_array_size_t length));
    API_FUNC(Il2CppArray*, array_new_specific, (Il2CppClass * arrayTypeInfo, il2cpp_array_size_t length));
    API_FUNC(Il2CppArray*, array_new_full, (Il2CppClass * array_class, il2cpp_array_size_t* lengths, il2cpp_array_size_t* lower_bounds));
    API_FUNC(Il2CppClass*, bounded_array_class_get, (Il2CppClass * element_class, uint32_t rank, bool bounded));
    API_FUNC(int, array_element_size, (Il2CppClass const* array_class));
    API_FUNC(Il2CppImage const*, assembly_get_image, (Il2CppAssembly const* assembly));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, class_for_each, (void (*klassReportFunc)(Il2CppClass* klass, void* userData), void* userData));
#endif
    API_FUNC(const Il2CppType*, class_enum_basetype, (Il2CppClass * klass));
    API_FUNC(bool, class_is_generic, (Il2CppClass const* klass));
    API_FUNC(bool, class_is_inflated, (Il2CppClass const* klass));
    API_FUNC(bool, class_is_assignable_from, (Il2CppClass * klass, Il2CppClass* oklass));
    API_FUNC(bool, class_is_subclass_of, (Il2CppClass * klass, Il2CppClass* klassc, bool check_interfaces));
    API_FUNC(bool, class_has_parent, (Il2CppClass * klass, Il2CppClass* klassc));
    API_FUNC(Il2CppClass*, class_from_il2cpp_type, (Il2CppType const* type));
    API_FUNC(Il2CppClass*, class_from_name, (Il2CppImage const* image, char const* namespaze, char const* name));
    API_FUNC(Il2CppClass*, class_from_system_type, (Il2CppReflectionType * type));
    API_FUNC(Il2CppClass*, class_get_element_class, (Il2CppClass * klass));
    API_FUNC(EventInfo const*, class_get_events, (Il2CppClass * klass, void** iter));
    API_FUNC(FieldInfo*, class_get_fields, (Il2CppClass * klass, void** iter));
    API_FUNC(Il2CppClass*, class_get_nested_types, (Il2CppClass * klass, void** iter));
    API_FUNC(Il2CppClass*, class_get_interfaces, (Il2CppClass * klass, void** iter));
    API_FUNC(PropertyInfo const*, class_get_properties, (Il2CppClass * klass, void** iter));
    API_FUNC(PropertyInfo const*, class_get_property_from_name, (Il2CppClass * klass, char const* name));
    API_FUNC(FieldInfo*, class_get_field_from_name, (Il2CppClass * klass, char const* name));
    API_FUNC(MethodInfo const*, class_get_methods, (Il2CppClass * klass, void** iter));
    API_FUNC(MethodInfo const*, class_get_method_from_name, (Il2CppClass const* klass, char const* name, int argsCount));
    API_FUNC(char const*, class_get_name, (Il2CppClass const* klass));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, type_get_name_chunked, (const Il2CppType* type, void (*chunkReportFunc)(void* data, void* userData), void* userData));
#endif
    API_FUNC(const char*, class_get_namespace, (const Il2CppClass* klass));
    API_FUNC(Il2CppClass*, class_get_parent, (Il2CppClass * klass));
    API_FUNC(Il2CppClass*, class_get_declaring_type, (Il2CppClass const* klass));
    API_FUNC(int32_t, class_instance_size, (Il2CppClass * klass));
    API_FUNC(size_t, class_num_fields, (Il2CppClass const* enumKlass));
    API_FUNC(bool, class_is_valuetype, (Il2CppClass const* klass));
    API_FUNC(int32_t, class_value_size, (Il2CppClass * klass, uint32_t* align));
    API_FUNC(bool, class_is_blittable, (Il2CppClass const* klass));
    API_FUNC(int, class_get_flags, (Il2CppClass const* klass));
    API_FUNC(bool, class_is_abstract, (Il2CppClass const* klass));
    API_FUNC(bool, class_is_interface, (Il2CppClass const* klass));
    API_FUNC(int, class_array_element_size, (Il2CppClass const* klass));
    API_FUNC(Il2CppClass*, class_from_type, (Il2CppType const* type));
    API_FUNC(Il2CppType const*, class_get_type, (Il2CppClass * klass));
    API_FUNC(uint32_t, class_get_type_token, (Il2CppClass * klass));
    API_FUNC(bool, class_has_attribute, (Il2CppClass * klass, Il2CppClass* attr_class));
    API_FUNC(bool, class_has_references, (Il2CppClass * klass));
    API_FUNC(bool, class_is_enum, (Il2CppClass const* klass));
    API_FUNC(Il2CppImage const*, class_get_image, (Il2CppClass * klass));
    API_FUNC(char const*, class_get_assemblyname, (Il2CppClass const* klass));
    API_FUNC(int, class_get_rank, (Il2CppClass const* klass));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(uint32_t, class_get_data_size, (const Il2CppClass* klass));
    API_FUNC(void*, class_get_static_field_data, (Il2CppClass const* klass));
#endif
#if defined(UNITY_2019) || defined(UNITY_2021)
    API_FUNC(size_t, class_get_bitmap_size, (const Il2CppClass* klass));
    API_FUNC(void, class_get_bitmap, (Il2CppClass * klass, size_t* bitmap));
#endif
    API_FUNC(bool, stats_dump_to_file, (const char* path));
    API_FUNC(uint64_t, stats_get_value, (Il2CppStat stat));
    API_FUNC(Il2CppDomain*, domain_get, ());
    API_FUNC(Il2CppAssembly const*, domain_assembly_open, (Il2CppDomain * domain, char const* name));
    API_FUNC(Il2CppAssembly const**, domain_get_assemblies, (Il2CppDomain const* domain, size_t* size));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, raise_exception, (Il2CppException*) );
#endif
    API_FUNC(Il2CppException*, exception_from_name_msg, (const Il2CppImage* image, const char* name_space, const char* name, const char* msg));
    API_FUNC(Il2CppException*, get_exception_argument_null, (char const* arg));
    API_FUNC(void, format_exception, (Il2CppException const* ex, char* message, int message_size));
    API_FUNC(void, format_stack_trace, (Il2CppException const* ex, char* output, int output_size));
    API_FUNC(void, unhandled_exception, (Il2CppException*) );
    API_FUNC(int, field_get_flags, (FieldInfo * field));
    API_FUNC(char const*, field_get_name, (FieldInfo * field));
    API_FUNC(Il2CppClass*, field_get_parent, (FieldInfo * field));
    API_FUNC(size_t, field_get_offset, (FieldInfo * field));
    API_FUNC(Il2CppType const*, field_get_type, (FieldInfo * field));
    API_FUNC(void, field_get_value, (Il2CppObject * obj, FieldInfo* field, void* value));
    API_FUNC(Il2CppObject*, field_get_value_object, (FieldInfo * field, Il2CppObject* obj));
    API_FUNC(bool, field_has_attribute, (FieldInfo * field, Il2CppClass* attr_class));
    API_FUNC(void, field_set_value, (Il2CppObject * obj, FieldInfo* field, void* value));
    API_FUNC(void, field_static_get_value, (FieldInfo * field, void* value));
    API_FUNC(void, field_static_set_value, (FieldInfo * field, void* value));
    API_FUNC(void, field_set_value_object, (Il2CppObject * instance, FieldInfo* field, Il2CppObject* value));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(bool, field_is_literal, (FieldInfo * field));
#endif
    API_FUNC(void, gc_collect, (int maxGenerations));
    API_FUNC(int32_t, gc_collect_a_little, ());
    API_FUNC(void, gc_disable, ());
    API_FUNC(void, gc_enable, ());
    API_FUNC(bool, gc_is_disabled, ());
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(int64_t, gc_get_max_time_slice_ns, ());
    API_FUNC(void, gc_set_max_time_slice_ns, (int64_t maxTimeSlice));
    API_FUNC(bool, gc_is_incremental, ());
#endif
    API_FUNC(int64_t, gc_get_used_size, ());
    API_FUNC(int64_t, gc_get_heap_size, ());
    API_FUNC(void, gc_wbarrier_set_field, (Il2CppObject * obj, void** targetAddress, void* object));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(bool, gc_has_strict_wbarriers, ());
    API_FUNC(void, gc_set_external_allocation_tracker, (void (*func)(void*, size_t, int)));
    API_FUNC(void, gc_set_external_wbarrier_tracker, (void (*func)(void**)));
    API_FUNC(void, gc_foreach_heap, (void (*func)(void* data, void* userData), void* userData));
    API_FUNC(void*, gc_alloc_fixed, (std::size_t size));
    API_FUNC(void, gc_free_fixed, (void* addr));
    API_FUNC(void, stop_gc_world, ());
    API_FUNC(void, start_gc_world, ());
#endif
    API_FUNC(uint32_t, gchandle_new, (Il2CppObject * obj, bool pinned));
    API_FUNC(uint32_t, gchandle_new_weakref, (Il2CppObject * obj, bool track_resurrection));
    API_FUNC(Il2CppObject*, gchandle_get_target, (uint32_t gchandle));
    API_FUNC(void, gchandle_free, (uint32_t gchandle));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, gchandle_foreach_get_target, (void (*func)(void* data, void* userData), void* userData));
    API_FUNC(uint32_t, object_header_size, ());
    API_FUNC(uint32_t, array_object_header_size, ());
    API_FUNC(uint32_t, offset_of_array_length_in_array_object_header, ());
    API_FUNC(uint32_t, offset_of_array_bounds_in_array_object_header, ());
    API_FUNC(uint32_t, allocation_granularity, ());
#endif
#if defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(
        void*,
        unity_liveness_allocate_struct,
        (Il2CppClass * filter,
         int max_object_count,
         il2cpp_register_object_callback callback,
         void* userdata,
         il2cpp_liveness_reallocate_callback reallocate)
    );
    API_FUNC(void, unity_liveness_finalize, (void* state));
    API_FUNC(void, unity_liveness_free_struct, (void* state));
#else
    API_FUNC(
        void*,
        unity_liveness_calculation_begin,
        (Il2CppClass * filter,
         int max_object_count,
         il2cpp_register_object_callback callback,
         void* userdata,
         il2cpp_WorldChangedCallback onWorldStarted,
         il2cpp_WorldChangedCallback onWorldStopped)
    );
    API_FUNC(void, unity_liveness_calculation_end, (void* state));
#endif
    API_FUNC(void, unity_liveness_calculation_from_root, (Il2CppObject * root, void* state));
    API_FUNC(void, unity_liveness_calculation_from_statics, (void* state));
    API_FUNC(Il2CppType const*, method_get_return_type, (MethodInfo const* method));
    API_FUNC(Il2CppClass*, method_get_declaring_type, (MethodInfo const* method));
    API_FUNC(char const*, method_get_name, (MethodInfo const* method));
    API_FUNC(MethodInfo const*, method_get_from_reflection, (Il2CppReflectionMethod const* method));
    API_FUNC(Il2CppReflectionMethod*, method_get_object, (MethodInfo const* method, Il2CppClass* refclass));
    API_FUNC(bool, method_is_generic, (MethodInfo const* method));
    API_FUNC(bool, method_is_inflated, (MethodInfo const* method));
    API_FUNC(bool, method_is_instance, (MethodInfo const* method));
    API_FUNC(uint32_t, method_get_param_count, (MethodInfo const* method));
    API_FUNC(Il2CppType const*, method_get_param, (MethodInfo const* method, uint32_t index));
    API_FUNC(Il2CppClass*, method_get_class, (MethodInfo const* method));
    API_FUNC(bool, method_has_attribute, (MethodInfo const* method, Il2CppClass* attr_class));
    API_FUNC(uint32_t, method_get_flags, (MethodInfo const* method, uint32_t* iflags));
    API_FUNC(uint32_t, method_get_token, (MethodInfo const* method));
    API_FUNC(char const*, method_get_param_name, (MethodInfo const* method, uint32_t index));

    // ONLY IF THE PROFILER EXISTS FOR UNITY_2019
    API_FUNC(void, profiler_install, (Il2CppProfiler * prof, Il2CppProfileFunc shutdown_callback));
    API_FUNC(void, profiler_set_events, (Il2CppProfileFlags events));
    API_FUNC(void, profiler_install_enter_leave, (Il2CppProfileMethodFunc enter, Il2CppProfileMethodFunc fleave));
    API_FUNC(void, profiler_install_allocation, (Il2CppProfileAllocFunc callback));
    API_FUNC(void, profiler_install_gc, (Il2CppProfileGCFunc callback, Il2CppProfileGCResizeFunc heap_resize_callback));
    API_FUNC(void, profiler_install_fileio, (Il2CppProfileFileIOFunc callback));
    API_FUNC(void, profiler_install_thread, (Il2CppProfileThreadFunc start, Il2CppProfileThreadFunc end));

    API_FUNC(uint32_t, property_get_flags, (PropertyInfo const* prop));
    API_FUNC(MethodInfo const*, property_get_get_method, (PropertyInfo const* prop));
    API_FUNC(MethodInfo const*, property_get_set_method, (PropertyInfo const* prop));
    API_FUNC(char const*, property_get_name, (PropertyInfo const* prop));
    API_FUNC(Il2CppClass*, property_get_parent, (PropertyInfo const* prop));
    API_FUNC(Il2CppClass*, object_get_class, (Il2CppObject * obj));
    API_FUNC(uint32_t, object_get_size, (Il2CppObject * obj));
    API_FUNC(MethodInfo const*, object_get_virtual_method, (Il2CppObject * obj, MethodInfo const* method));
    API_FUNC(Il2CppObject*, object_new, (Il2CppClass const* klass));
    // Always returns (void*, (obj + 1)
    API_FUNC(void*, object_unbox, (Il2CppObject * obj));
    // If klass is not a ValueType, returns (Il2CppObject*, (*data), else boxes
    API_FUNC(Il2CppObject*, value_box, (Il2CppClass * klass, void* data));
    API_FUNC(void, monitor_enter, (Il2CppObject * obj));
    API_FUNC(bool, monitor_try_enter, (Il2CppObject * obj, uint32_t timeout));
    API_FUNC(void, monitor_exit, (Il2CppObject * obj));
    API_FUNC(void, monitor_pulse, (Il2CppObject * obj));
    API_FUNC(void, monitor_pulse_all, (Il2CppObject * obj));
    API_FUNC(void, monitor_wait, (Il2CppObject * obj));
    API_FUNC(bool, monitor_try_wait, (Il2CppObject * obj, uint32_t timeout));
    API_FUNC(Il2CppObject*, runtime_invoke, (MethodInfo const* method, void* obj, void** params, Il2CppException** exc));
    API_FUNC(
        Il2CppObject*,
        runtime_invoke_convert_args,
        (MethodInfo const* method, void* obj, Il2CppObject** params, int paramCount, Il2CppException** exc)
    );
    API_FUNC(void, runtime_class_init, (Il2CppClass * klass));
    API_FUNC(void, runtime_object_init, (Il2CppObject * obj));
    API_FUNC(void, runtime_object_init_exception, (Il2CppObject * obj, Il2CppException** exc));
    API_FUNC(void, runtime_unhandled_exception_policy_set, (Il2CppRuntimeUnhandledExceptionPolicy value));
    API_FUNC(int32_t, string_length, (Il2CppString * str));
    API_FUNC(Il2CppChar*, string_chars, (Il2CppString * str));
    API_FUNC(Il2CppString*, string_new, (char const* str));
    API_FUNC(Il2CppString*, string_new_len, (char const* str, uint32_t length));
    API_FUNC(Il2CppString*, string_new_utf16, (Il2CppChar const* text, int32_t len));
    API_FUNC(Il2CppString*, string_new_wrapper, (char const* str));
    API_FUNC(Il2CppString*, string_intern, (Il2CppString * str));
    API_FUNC(Il2CppString*, string_is_interned, (Il2CppString * str));
    API_FUNC(Il2CppThread*, thread_current, ());
    API_FUNC(Il2CppThread*, thread_attach, (Il2CppDomain * domain));
    API_FUNC(void, thread_detach, (Il2CppThread * thread));
#if defined(UNITY_2019) || defined(UNITY_2021)
    API_FUNC(Il2CppThread**, thread_get_all_attached_threads, (size_t* size));
#endif
    API_FUNC(bool, is_vm_thread, (Il2CppThread * thread));
    API_FUNC(void, current_thread_walk_frame_stack, (Il2CppFrameWalkFunc func, void* user_data));
    API_FUNC(void, thread_walk_frame_stack, (Il2CppThread * thread, Il2CppFrameWalkFunc func, void* user_data));
    API_FUNC(bool, current_thread_get_top_frame, (Il2CppStackFrameInfo * frame));
    API_FUNC(bool, thread_get_top_frame, (Il2CppThread * thread, Il2CppStackFrameInfo* frame));
    API_FUNC(bool, current_thread_get_frame_at, (int32_t offset, Il2CppStackFrameInfo* frame));
    API_FUNC(bool, thread_get_frame_at, (Il2CppThread * thread, int32_t offset, Il2CppStackFrameInfo* frame));
    API_FUNC(int32_t, current_thread_get_stack_depth, ());
    API_FUNC(int32_t, thread_get_stack_depth, (Il2CppThread * thread));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, override_stack_backtrace, (Il2CppBacktraceFunc stackBacktraceFunc));
#endif
    API_FUNC(Il2CppObject*, type_get_object, (const Il2CppType* type));
    API_FUNC(int, type_get_type, (Il2CppType const* type));
    API_FUNC(Il2CppClass*, type_get_class_or_element_class, (Il2CppType const* type));
    API_FUNC(char*, type_get_name, (Il2CppType const* type));
    API_FUNC(bool, type_is_byref, (Il2CppType const* type));
    API_FUNC(uint32_t, type_get_attrs, (Il2CppType const* type));
    API_FUNC(bool, type_equals, (Il2CppType const* type, Il2CppType const* otherType));
    API_FUNC(char*, type_get_assembly_qualified_name, (Il2CppType const* type));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(bool, type_is_static, (const Il2CppType* type));
    API_FUNC(bool, type_is_pointer_type, (Il2CppType const* type));
#endif
    API_FUNC(const Il2CppAssembly*, image_get_assembly, (const Il2CppImage* image));
    API_FUNC(char const*, image_get_name, (Il2CppImage const* image));
    API_FUNC(char const*, image_get_filename, (Il2CppImage const* image));
    API_FUNC(MethodInfo const*, image_get_entry_point, (Il2CppImage const* image));
    API_FUNC(size_t, image_get_class_count, (Il2CppImage const* image));
    API_FUNC(Il2CppClass const*, image_get_class, (Il2CppImage const* image, size_t index));
    API_FUNC(Il2CppManagedMemorySnapshot*, capture_memory_snapshot, ());
    API_FUNC(void, free_captured_memory_snapshot, (Il2CppManagedMemorySnapshot * snapshot));
    API_FUNC(void, set_find_plugin_callback, (Il2CppSetFindPlugInCallback method));
    API_FUNC(void, register_log_callback, (Il2CppLogCallback method));
    API_FUNC(void, debugger_set_agent_options, (char const* options));
    API_FUNC(bool, is_debugger_attached, ());
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, register_debugger_agent_transport, (Il2CppDebuggerTransport * debuggerTransport));
    API_FUNC(bool, debug_get_method_info, (MethodInfo const*, Il2CppMethodDebugInfo* methodDebugInfo));
#endif
    API_FUNC(void, unity_install_unitytls_interface, (const void* unitytlsInterfaceStruct));
    API_FUNC(Il2CppCustomAttrInfo*, custom_attrs_from_class, (Il2CppClass * klass));
    API_FUNC(Il2CppCustomAttrInfo*, custom_attrs_from_method, (MethodInfo const* method));
    API_FUNC(Il2CppObject*, custom_attrs_get_attr, (Il2CppCustomAttrInfo * ainfo, Il2CppClass* attr_klass));
    API_FUNC(bool, custom_attrs_has_attr, (Il2CppCustomAttrInfo * ainfo, Il2CppClass* attr_klass));
    API_FUNC(Il2CppArray*, custom_attrs_construct, (Il2CppCustomAttrInfo * cinfo));
    API_FUNC(void, custom_attrs_free, (Il2CppCustomAttrInfo * ainfo));
#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(void, class_set_userdata, (Il2CppClass * klass, void* userdata));
    API_FUNC(int, class_get_userdata_offset, ());
#endif

    // MANUALLY DEFINED CONST DEFINITIONS
    API_FUNC(Il2CppType const*, class_get_type_const, (Il2CppClass const* klass));
    API_FUNC(char const*, class_get_name_const, (Il2CppClass const* klass));
    API_FUNC(Il2CppClass*, type_get_class, (Il2CppType * type));

    // SELECT NON-API LIBIL2CPP FUNCTIONS:
    API_FUNC(bool, Class_Init, (Il2CppClass * klass));

    API_FUNC(Il2CppClass*, MetadataCache_GetTypeInfoFromHandle, (Il2CppMetadataTypeHandle index));
    API_FUNC(Il2CppClass*, MetadataCache_GetTypeInfoFromTypeIndex, (TypeIndex index));

    API_FUNC(Il2CppClass*, GlobalMetadata_GetTypeInfoFromTypeDefinitionIndex, (TypeDefinitionIndex index));
    API_FUNC(Il2CppClass*, GlobalMetadata_GetTypeInfoFromHandle, (Il2CppMetadataTypeHandle index));

#if defined(UNITY_2019) || defined(UNITY_2021) || defined(UNITY_6)
    API_FUNC(std::string, _Type_GetName_, (const Il2CppType* type, Il2CppTypeNameFormat format));
#else
    API_FUNC(gnu_string, _Type_GetName_, (const Il2CppType* type, Il2CppTypeNameFormat format));
#endif
    API_FUNC(void, GC_free, (void* addr));

    API_FUNC(void, GarbageCollector_SetWriteBarrier, (void** ptr));
    API_FUNC(void*, GarbageCollector_AllocateFixed, (size_t sz, void* descr));

    API_FUNC(Il2CppClass*, Class_FromIl2CppType, (Il2CppType * typ));
    API_FUNC(Il2CppClass*, Class_GetPtrClass, (Il2CppClass * elementClass));
    API_FUNC(Il2CppClass*, GenericClass_GetClass, (Il2CppGenericClass * gclass));
    API_FUNC(Il2CppClass*, GenericClass_CreateClass, (Il2CppGenericClass * gclass, bool throwOnError));
#if defined(UNITY_2019) || defined(UNITY_2021)
    API_FUNC(Il2CppAssemblyVector*, Assembly_GetAllAssemblies, ());
#endif
    extern bool has_gc_funcs;

    // You must i2c::functions::free the char* when you are done with it
    extern char* Type_GetName(Il2CppType const* type, Il2CppTypeNameFormat format);
    extern void const* s_GlobalMetadata;
    extern Il2CppGlobalMetadataHeader const* s_GlobalMetadataHeader;
    extern Il2CppMetadataRegistration const* s_Il2CppMetadataRegistration;

    extern Il2CppDefaults const* defaults;
    extern void find_il2cpp_defaults(Paper::LoggerContext const& logger);

#if !defined(UNITY_2019) && !defined(UNITY_2021)
    extern Il2CppAssemblyVector* s_Assemblies;
    extern void find_s_Assemblies(Paper::LoggerContext const& logger);
#endif

    // must be done on-demand because the pointers aren't necessarily correct at the time of il2cpp_functions::Init
    void CheckS_GlobalMetadata();

    // COPIES OF FREQUENTLY INLINED NON-API LIBIL2CPP FUNCTIONS:
    char const* MetadataCache_GetStringFromIndex(StringIndex index);
    Il2CppTypeDefinition const* MetadataCache_GetTypeDefinitionFromIndex(TypeDefinitionIndex index);
    TypeDefinitionIndex MetadataCache_GetExportedTypeFromIndex(TypeDefinitionIndex index);
    Il2CppGenericContainer const* MetadataCache_GetGenericContainerFromIndex(GenericContainerIndex index);
    Il2CppGenericParameter const* MetadataCache_GetGenericParameterFromIndex(GenericParameterIndex index);
    Il2CppClass* MetadataCache_GetNestedTypeFromIndex(NestedTypeIndex index);
    TypeDefinitionIndex MetadataCache_GetIndexForTypeDefinition(Il2CppClass const* typeDefinition);
    TypeDefinitionIndex MetadataCache_GetIndexForTypeDefinition(Il2CppTypeDefinition const* typeDefinition);
    GenericParameterIndex MetadataCache_GetGenericParameterIndexFromParameter(Il2CppMetadataGenericParameterHandle handle);
    Il2CppTypeDefinition const* MetadataCache_GetTypeDefinition(Il2CppClass* klass);
    GenericParameterIndex MetadataCache_GetGenericContainerIndex(Il2CppClass* klass);

#if !defined(UNITY_2019) && !defined(UNITY_2021)
    Il2CppAssemblyVector* Assembly_GetAllAssemblies();
#endif

    // Whether all of the il2cpp functions have been initialized or not
    extern bool initialized;
    // Initializes all of the IL2CPP functions via dlopen and dlsym for use.
    void initialize() noexcept;
}

#undef API_FUNC

// Okay, so because we know that GC isn't overwriting heap (since it just calls the same shared calloc/malloc impls)
// we are confident that a new operator here isn't necessary or useful.
// We can safely say that the heap is shared properly, abeit without references.
// If references ARE desired, use one of the gc allocation functions in here expicitly.

namespace i2c {
    /// @brief Returns an allocated instance of the provided size that will not be written over by future GC allocations and holds references.
    /// You MUST use the gc_free_specific function defined here to destroy it.
    /// This function fallsback to calloc if no GC_Alloc or GC_Free implementations are found via xref/sigscan.
    /// @param sz The size to allocate an instance of.
    /// @return The allocated instance.
    [[nodiscard]] void* gc_alloc_specific(size_t sz) noexcept;

    /// @brief Deletes the provided allocated instance from the gc_alloc_specific function defined here.
    /// Other pointers will cause undefined behavior.
    /// This function will call GC_free if there is both a GC_Alloc and GC_Free implementation available, free otherwise.
    /// @param sz The pointer to free explicitly.
    /// @return The allocated instance.
    void gc_free_specific(void* ptr) noexcept;

    /// @brief Reallocation implementation is equivalent to: alloc + free
    /// @param ptr The pointer to resize.
    /// @param new_size The new size of the memory.
    /// @return The resized instance.
    [[nodiscard]] void* gc_realloc_specific(void* ptr, size_t new_size) noexcept;

    /// @brief EXTREMEMLY UNSAFE ALLOCATION! THIS SHOULD BE AVOIDED UNLESS YOU KNOW WHAT YOU ARE DOING!
    /// This function allocates a GC-able object of the size provided by manipulating an existing Il2CppClass' instance_size.
    /// This is VERY DANGEROUS (and NOT THREAD SAFE!) and may cause all sorts of race conditions. Use at your own risk.
    /// @param size The size to allocate the unsafe object with.
    /// @return The returned GC-allocated instance.
    [[deprecated("DO NOT USE")]] void* __allocate_unsafe(std::size_t size) noexcept;

    /// @brief Resolves the provided icall, throwing an i2c::trace_exception with backtrace information if failed.
    /// Does NOT cache the resolved method pointer.
    /// Also does NOT perform any type checking of parameters, so make sure you check your parameters and return types!
    /// @tparam R The return type of the function to resolve
    /// @tparam TArgs The arguments of the function to resolve
    /// @param name The name of the icall to resolve
    /// @return The resolved function pointer, will always be valid or throws an i2c::trace_exceptionon.
    template <typename R, typename... TArgs>
    function_ptr_t<R, TArgs...> resolve_icall(std::string_view name) {
        functions::initialize();
        if (auto out = reinterpret_cast<function_ptr_t<R, TArgs...>>(functions::resolve_icall(name.data()))) {
            return out;
        }
        throw i2c::trace_exception(fmt::format("Failed to resolve_icall for: {}!", name.data()));
    }
}

#pragma pack(pop)
